dist: trusty
os: linux
language: java
jdk: oraclejdk8

before_install:
 - chmod a+x ./mvnw
 
deploy:
  strategy: api
  provider: heroku
  api_key: "3a761741-7735-4a86-ab54-647bc72de6f4"
  app: CursoSpringBoot1
