dist: trusty
os: linux
language: java
jdk: oraclejdk8

before_install:
 - chmod a+x ./mvnw

branches:
  only:
    - master

deploy:
  strategy: api
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: spring-curso-boot
